apiVersion : apps/v1
kind: Deployment
metadata:
  name: "duketestk8s-6240"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "duketestk8s-6240"
  template:
    metadata:
      labels:
        app: "duketestk8s-6240"
    spec:
      containers:
        - name: "duketestk8s-6240"
          image: "duketset1.azurecr.io/duketestk8s"
          ports:
          - containerPort: 80