on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testforechkingowner.azurecr.io
        username: ${{ secrets.acr_testforechkingowner_username }}
        password: ${{ secrets.acr_testforechkingowner_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t testforechkingowner.azurecr.io/duketestk8s:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push testforechkingowner.azurecr.io/duketestk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_duketestk8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep duketestk8s9d20 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace duketestk8s9d20`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: duketestk8s9d20
        container-registry-url: testforechkingowner.azurecr.io
        container-registry-username: ${{ secrets.acr_testforechkingowner_username }}
        container-registry-password: ${{ secrets.acr_testforechkingowner_password }}
        secret-name: duketestk8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: duketestk8s9d20
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          testforechkingowner.azurecr.io/duketestk8s:${{ github.sha }}
        imagepullsecrets: |
          duketestk8sdockerauth
