on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n testforechkingowner -g testforechkingownerac91-rg --location "East Asia" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n testforechkingowner --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n testforechkingowner --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n testforechkingowner --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: testforechkingowner.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t testforechkingowner.azurecr.io/duketestk8s:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push testforechkingowner.azurecr.io/duketestk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_duketestk8s_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep duketestk8sa47f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace duketestk8sa47f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: duketestk8sa47f
        container-registry-url: testforechkingowner.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: duketestk8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: duketestk8sa47f
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          testforechkingowner.azurecr.io/duketestk8s:${{ github.sha }}
        imagepullsecrets: |
          duketestk8sdockerauth   
